AWSTemplateFormatVersion: "2010-09-09"
Description: Create an S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket

Resources:
  DtccPovBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketName:
    Description: "The name of the S3 bucket"
    Value: !Ref DtccPovBucket
